def print_menu():
    print("\n" + "="*50)
    print("  EcoRide Urban Mobility System")
    print("="*50)
    print("1.  Add Hub")
    print("2.  Add Vehicle to Hub")
    print("3.  Display Vehicles by Hub")
    print("4.  List All Hubs")
    print("5.  Search by Battery Level")
    print("6.  Display Vehicles by Type")
    print("7.  Display Fleet Analytics")
    print("8.  Display Vehicles Sorted by Model")
    print("9.  Display Vehicles Sorted by Battery")
    print("10. Display Vehicles Sorted by Rental Price")
    print("11. Save Fleet Data to CSV")
    print("12. Load Fleet Data from CSV")
    print("13. Save Fleet Data to JSON")
    print("14. Load Fleet Data from JSON")
    print("0.  Exit")
    print("="*50)
